const placeholderImage = "/2k-logo-black-biale-tlo.png";

export const realizationsData = [
  {
    id: "korekta-lakieru",
    description: "Korekta lakieru",
    images: [placeholderImage, placeholderImage, placeholderImage],
    image: placeholderImage,
    largeImage: placeholderImage,
    largeImageWidth: 1920,
    gradient: "linear-gradient(rgba(63, 59, 59, 0.5), rgba(40, 31, 31, 0.5))",
    customClass: "korektaLakieru",
    mobileClass: "korektaLakieruMobile",
  },
  {
    id: "powloka-ceramiczna",
    description: "Powłoka ceramiczna i elastomerowa",
    images: [placeholderImage, placeholderImage, placeholderImage],
    image: placeholderImage,
    largeImage: placeholderImage,
    largeImageWidth: 1920,
    gradient: "linear-gradient(rgba(38, 32, 32, 0.5), rgba(40, 31, 31, 0.5))",
    customClass: "powlokaCeramiczna",
    mobileClass: "powlokaCeramicznaMobile",
  },
  {
    id: "folia-ppf",
    description: "Zabezpieczenie folią PPF",
    images: [placeholderImage, placeholderImage],
    image: placeholderImage,
    largeImage: placeholderImage,
    largeImageWidth: 1920,
    gradient: "linear-gradient(rgba(38, 32, 32, 0.5), rgba(40, 31, 31, 0.5))",
    customClass: "foliaPPF",
    mobileClass: "foliaPPFMobile",
  },
  {
    id: "pranie-tapicerki",
    description: "Pranie tapicerki",
    images: [placeholderImage, placeholderImage, placeholderImage],
    image: placeholderImage,
    largeImage: placeholderImage,
    largeImageWidth: 1920,
    gradient: "linear-gradient(rgba(63, 59, 59, 0.5), rgba(40, 31, 31, 0.5))",
    customClass: "pranieTapicerki",
    mobileClass: "pranieTapicerkiMobile",
  },
  {
    id: "renowacja-skor",
    description: "Renowacja skór",
    images: [
      placeholderImage,
      placeholderImage,
      placeholderImage,
      placeholderImage,
    ],
    image: placeholderImage,
    largeImage: placeholderImage,
    largeImageWidth: 1920,
    gradient: "linear-gradient(rgba(63, 59, 59, 0.5), rgba(40, 31, 31, 0.5))",
    customClass: "renowacjaSkor",
    mobileClass: "renowacjaSkorMobile",
  },
  {
    id: "detailing-wnetrza",
    description: "Detailing wnętrza",
    images: [placeholderImage, placeholderImage, placeholderImage],
    image: placeholderImage,
    largeImage: placeholderImage,
    largeImageWidth: 1920,
    gradient: "linear-gradient(rgba(63, 59, 59, 0.5), rgba(40, 31, 31, 0.5))",
    customClass: "detailingWnetrza",
    mobileClass: "detailingWnetrzaMobile",
  },
  {
    id: "regeneracja-reflektorow",
    description: "Regeneracja reflektorów",
    images: [placeholderImage, placeholderImage],
    image: placeholderImage,
    largeImage: placeholderImage,
    largeImageWidth: 1920,
    gradient: "linear-gradient(rgba(63, 59, 59, 0.5), rgba(40, 31, 31, 0.5))",
    customClass: "regeneracjaReflektorow",
    mobileClass: "regeneracjaReflektorowMobile",
  },
  {
    id: "przyciemnianie-szyb",
    description: "Przyciemnianie szyb",
    images: [placeholderImage, placeholderImage],
    image: placeholderImage,
    largeImage: placeholderImage,
    largeImageWidth: 1920,
    gradient: "linear-gradient(rgba(63, 59, 59, 0.5), rgba(40, 31, 31, 0.5))",
    customClass: "przyciemnianieSzyb",
    mobileClass: "przyciemnianieSzybMobile",
  },
  {
    id: "auto-detailing",
    description: "Auto Detailing – pakiet kompleksowy",
    images: [placeholderImage, placeholderImage, placeholderImage],
    image: placeholderImage,
    largeImage: placeholderImage,
    largeImageWidth: 1920,
    gradient: "linear-gradient(rgba(63, 59, 59, 0.5), rgba(40, 31, 31, 0.5))",
    customClass: "autoDetailing",
    mobileClass: "autoDetailingMobile",
  },
];
